Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network "private_network", type: "dhcp"
      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.provision "shell", inline: <<-SHELL
        # Install Docker
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

        # Install kubeadm, kubelet, and kubectl
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl
        curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
        sudo touch /etc/apt/sources.list.d/kubernetes.list
        echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
        sudo apt-get update
        sudo apt-get install -y kubelet kubeadm kubectl
        sudo apt-mark hold kubelet kubeadm kubectl
      SHELL
    end
  end
end
#/rm /etc/containerd/config.toml > need to remove previously staged
#init kubeadm sudo kubeadm init --pod-network-cidr=192.168.0.0/16 in master
sudo kubeadm join 10.0.2.15:6443 --token fmwyp6.k2sdk3a6odhe02dq \
        --discovery-token-ca-cert-hash sha256:8b11ea1ae711e468d6eeb9f6ca0a98c5201c84b22b27b7c81ed5ea18a9be9e67 